/*Closure is a runtime object created by the lambda expression.
  Lambda expression: actual compile-time syntax we write in our code.
  (e.g., [](int x){ return x+1; })
  Closure: concrete runtime object generated by the compile when that 
  lambda expression is executed.
*/
#include<iostream>
#include<algorithm>
#include<functional>

using namespace std;

/*// The hidden closure class type
  class CompilerGeneratedClosureName {
    private:
      int factor; // Captured variable becomes a member variable
    public:
      CompilerGeneratedClosureName(int f) : factor(f) {}

      // The lambda body becomes the call operator
      int operator()(int value) const {
        return value * factor;
      }
  };

  // At runtime, the closure object is instantiated:
  int factor = 5;
  CompilerGeneratedClosureName my_closure(factor);
  */

function<int()> getDanglingClosure()
{
 int local_var = 5;
 return [&local_var](){
    return local_var;
 };
}

int main()
{
 int factor, value;
 cin>>factor>>value;
 auto my_closure = [factor](int x){
   return factor*x;
 };
 cout<<my_closure(value)<<endl;
 auto bad_closure = getDanglingClosure();
 auto x = bad_closure();
 /* UNDEFINED BEHAVIOR: Reading 'result' will output garbage values or crash, 
    because it tried to read memory that was already deallocated. */ 
 cout<<x<<endl;
 return 0;
}